services:
  dira:
    build:
      target: dev
    container_name: dira-dev
    # Use the correct script from your package.json:
    command: npm run start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development